### ISSUE TITLE
v5.1.7 fails with "[error] 201#201: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.30.32.2"

### ISSUE THREAD

**Issue by 7wells** [dfigus/addon-tvheadend#175] opened 2024-04-23 16:07 UTC
Sorry, Daniel, please delete this "issue", as it was resolved after 2 HA restarts. :)

**Comment by dfigus** [comment] 2024-04-24 12:22
Hi @7wells,

see also #174 - those are errors which should not impact the functionality. However #176 should avoid those errors. I'll create a release as soon as the build is complete.

**Comment by dfigus** [comment] 2024-04-24 13:01
Closing this one as a duplicate of #174

**Closed as not planned** 2024-04-24 13:02 UTC
